spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service-db
      database: ivmsDB
      host: localhost
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

server:
  port: 8084
