package com.challenge.userservice.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "users")
public class User {
    @Id
    private String userId;
    private String username;
    private String email;
    private String password;
    // Add other fields as needed

    // Constructors, getters, setters, and other methods can be generated by Lombok
}
